// src/app/(payload)/admin/importMap.js
// Auto-generated by `pnpm payload generate:importmap`. Re-run that command
// any time a custom admin component is added; do not hand-edit this file.
export const importMap = {}
